const $=s=>document.querySelector(s),safe=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c]));
let orders=[];
async function api(url,options={}){const r=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}),d=await r.json();if(r.status===401||r.status===403){location.href="auth.html";throw Error("Buyer sign-in required")}if(!r.ok)throw Error(d.error||"Request failed");return d}
async function load(){orders=await api("/api/buyer/orders");render();addPreviews()}
async function addPreviews(){await Promise.all(orders.map(async(o,i)=>{try{const detail=await api(`/api/buyer/orders/${encodeURIComponent(o.id)}`);const item=detail.items?.[0];if(!item?.image_url)return;const row=document.querySelectorAll(".order")[i];if(!row)return;const preview=document.createElement("div");preview.className="order-preview";preview.innerHTML=`<img src="${safe(item.image_url)}" alt=""><span>${safe(item.name)}${detail.items.length>1?` + ${detail.items.length-1} more item`:""}</span>`;row.insertBefore(preview,row.querySelector(".order-body"));}catch{}}))}
function render(){
  $("#orders").innerHTML=orders.length?orders.map(o=>`<article class="order"><header class="order-head"><div><strong>Order ${safe(o.id)}</strong><small>${new Date(o.created_at+"Z").toLocaleDateString()} · ${safe(o.store_name)}</small></div><strong>${safe(o.currency)} ${Number(o.total).toLocaleString()}</strong></header><div class="order-body"><div><small>ORDER STATUS</small><br><span class="status">${safe(o.status)}</span></div><div><small>DELIVERY</small><br><strong>${safe(o.destination)}</strong>${o.carrier?`<small>${safe(o.carrier)} · ${safe(o.tracking_number)}</small>${o.estimated_delivery?`<small>Estimated ${new Date(o.estimated_delivery+"T12:00:00").toLocaleDateString()}</small>`:""}${o.tracking_url?`<a href="${safe(o.tracking_url)}" target="_blank" rel="noopener">Track with carrier ↗</a>`:""}`:""}</div><div><button class="help" data-detail="${safe(o.id)}">View order details</button>${o.dispute_status!=="none"?`<span class="dispute">Dispute: ${safe(o.dispute_status.replaceAll("_"," "))}</span>`:`<button class="help" data-dispute="${safe(o.id)}">Get help with order</button>`}</div></div>${o.tracking_events?.length?`<div class="order-body"><div><small>TRACKING TIMELINE</small>${o.tracking_events.map(e=>`<p><strong>${safe(e.message)}</strong><br><small>${new Date(e.created_at+"Z").toLocaleString()}</small></p>`).join("")}</div></div>`:""}<div class="order-detail" id="detail-${safe(o.id)}" hidden></div></article>`).join(""):'<div class="empty"><strong>No orders yet</strong><p>Products you purchase will appear here.</p></div>';
  document.querySelectorAll("[data-detail]").forEach(b=>b.onclick=()=>showDetail(b.dataset.detail));document.querySelectorAll("[data-dispute]").forEach(b=>b.onclick=()=>openDispute(b.dataset.dispute))
}
async function showDetail(id){const box=$("#detail-"+CSS.escape(id));if(!box)return;if(!box.hidden){box.hidden=true;return}try{const o=await api(`/api/buyer/orders/${encodeURIComponent(id)}`);box.innerHTML=`<div class="detail-card"><h3>Order details</h3>${o.items.map(i=>`<div class="detail-line"><span>${safe(i.name)}${i.variant_label?` · ${safe(i.variant_label)}`:""} × ${i.quantity}</span><strong>${safe(o.currency)} ${Number(i.price*i.quantity).toLocaleString()}</strong></div>`).join("")}<div class="detail-line"><span>Products</span><strong>${safe(o.currency)} ${Number(o.subtotal).toLocaleString()}</strong></div><div class="detail-line"><span>Delivery</span><strong>${safe(o.currency)} ${Number(o.delivery_fee).toLocaleString()}</strong></div><div class="detail-line total"><span>Total</span><strong>${safe(o.currency)} ${Number(o.total).toLocaleString()}</strong></div></div>`;box.hidden=false}catch(e){toast(e.message)}}
function openDispute(id){$("#modalContent").innerHTML=`<span class="kicker">SOKO SUPPORT</span><h2>Get help with ${safe(id)}</h2><p>Opening a dispute asks the Soko Trust team to review the buyer, merchant and order records.</p><form id="disputeForm"><textarea name="reason" required minlength="10" placeholder="Tell us what went wrong"></textarea><button class="primary">Open dispute →</button></form>`;$("#backdrop").classList.add("open");$("#disputeForm").addEventListener("submit",async e=>{e.preventDefault();try{await api(`/api/buyer/orders/${encodeURIComponent(id)}/dispute`,{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});close();await load();toast("Dispute opened for Soko review")}catch(err){toast(err.message)}})}
function close(){$("#backdrop").classList.remove("open")}$("#close")?.addEventListener("click",close);$("#backdrop")?.addEventListener("click",e=>{if(e.target===$("#backdrop"))close()});$("#logout")?.addEventListener("click",async()=>{await api("/api/auth/logout",{method:"POST"});location.href="auth.html"});let timer;function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");clearTimeout(timer);timer=setTimeout(()=>$("#toast").classList.remove("show"),2500)}load().catch(()=>{});
