const products = [
  {id:1,name:"Premium jollof spice blend",merchant:"Nana's Kitchen",country:"🇬🇭 Ghana",market:"Ghana",currency:"GHS",category:"food",price:145,emoji:"🫙",color:"#e8b65d"},
  {id:2,name:"Handwoven Bolga basket",merchant:"Aduke Collective",country:"🇬🇭 Ghana",market:"Ghana",currency:"GHS",category:"home",price:520,emoji:"🧺",color:"#d59a69"},
  {id:3,name:"Indigo Adire tote",merchant:"Ìtàn Studio",country:"🇳🇬 Nigeria",market:"Nigeria",currency:"NGN",category:"fashion",price:48000,emoji:"👜",color:"#b9c9dd"},
  {id:4,name:"Raw African black soap set",merchant:"Zuri Botanics",country:"🇰🇪 Kenya",market:"Kenya",currency:"KES",category:"beauty",price:3900,emoji:"🧼",color:"#bed0ab"},
  {id:5,name:"Roasted Kenyan coffee",merchant:"Kijani Roasters",country:"🇰🇪 Kenya",market:"Kenya",currency:"KES",category:"food",price:2650,emoji:"☕",color:"#c9a587"},
  {id:6,name:"Beaded statement collar",merchant:"Nairobi Beadworks",country:"🇰🇪 Kenya",market:"Kenya",currency:"KES",category:"fashion",price:5200,emoji:"📿",color:"#eab39a"},
  {id:7,name:"Aso-oke cushion cover",merchant:"Ile Textiles",country:"🇳🇬 Nigeria",market:"Nigeria",currency:"NGN",category:"home",price:56000,emoji:"🪡",color:"#d4bfdf"},
  {id:8,name:"Whipped shea body butter",merchant:"Tamale Naturals",country:"🇬🇭 Ghana",market:"Ghana",currency:"GHS",category:"beauty",price:210,emoji:"🧴",color:"#eee0aa"}
];
const savedMerchant=JSON.parse(localStorage.getItem("sokoMerchant")||"null");const savedMerchantProducts=JSON.parse(localStorage.getItem("sokoMerchantProducts")||"[]");if(savedMerchant){const countryInfo={Nigeria:{currency:"NGN",flag:"🇳🇬"},Ghana:{currency:"GHS",flag:"🇬🇭"},Kenya:{currency:"KES",flag:"🇰🇪"}}[savedMerchant.country];savedMerchantProducts.filter(p=>p.active).forEach(p=>products.unshift({...p,merchant:savedMerchant.name,country:`${countryInfo.flag} ${savedMerchant.country}`,market:savedMerchant.country,currency:countryInfo.currency}))}
async function loadDatabaseProducts(){try{const response=await fetch("/api/products"),items=await response.json();if(response.ok){items.forEach(item=>products.unshift({...item,id:`db-${item.id}`,backendId:item.id}));renderProducts();const pending=localStorage.getItem("sokoPendingProduct");if(pending){localStorage.removeItem("sokoPendingProduct");const selection=JSON.parse(pending);await addToCart(`db-${selection.productId}`,selection);toggleCart(true)}}}catch{}}
let cart=[];let filter="all",searchTerm="",countryFilter="all",favorites=new Set();let checkoutStep=1;let deliveryDetails={};let currentOrder=null;
const $=s=>document.querySelector(s);const money=(value,currency)=>`${currency} ${value.toLocaleString("en-GB")}`;const safe=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const paymentRoutes={NGN:{method:"Bank transfer",bank:"Soko Merchant Demo Bank",recipient:"Merchant collection account",account:"0123456789"},GHS:{method:"Mobile money",bank:"MTN MoMo (demo)",recipient:"Merchant collection wallet",account:"024 000 0000"},KES:{method:"M-PESA",bank:"M-PESA Paybill (demo)",recipient:"Merchant collection till",account:"555000"}};

function renderProducts(){
  const list=products.filter(p=>(filter==="all"||p.category===filter)&&(countryFilter==="all"||p.market===countryFilter)&&(!searchTerm||`${p.name} ${p.merchant} ${p.category}`.toLowerCase().includes(searchTerm)));
  $("#resultCount").textContent=`${list.length} product${list.length===1?"":"s"}`;$("#products").innerHTML=list.length?list.map(p=>`<article class="shop-card"><div class="shop-art" style="background:${p.color}">${p.image_url?`<a class="product-link" href="product.html?id=${p.backendId}"><img src="${p.image_url}" alt="${p.name}" loading="lazy"></a>`:`<span>${p.emoji}</span>`}<div class="country-tag">${p.country}</div>${p.backendId?`<button class="favorite-button ${favorites.has(p.backendId)?"saved":""}" data-favorite="${p.backendId}" aria-label="Save ${p.name}">${favorites.has(p.backendId)?"♥":"♡"}</button>`:""}<button class="add-button" data-add="${p.id}" aria-label="Add ${p.name} to bag">+</button></div><div class="shop-info"><a class="merchant-link" href="${p.merchant_id?`store.html?id=${p.merchant_id}`:"#"}">${p.merchant}</a><h3>${p.backendId?`<a href="product.html?id=${p.backendId}">${p.name}</a>`:p.name}</h3><div class="price-row"><strong>${money(p.price,p.currency)}</strong><span class="${p.stock>0&&p.stock<5?"low-stock":""}">${p.stock===0?"Sold out":p.stock>0&&p.stock<5?`Only ${p.stock} left`:`Pay in ${p.currency}`}</span></div></div></article>`).join(""):`<div class="catalog-empty"><strong>No products found</strong><p>Try another search or filter.</p></div>`;
  document.querySelectorAll("[data-add]").forEach(b=>b.addEventListener("click",()=>addToCart(b.dataset.add)));
  document.querySelectorAll("[data-favorite]").forEach(b=>b.addEventListener("click",()=>toggleFavorite(Number(b.dataset.favorite))));
}
async function toggleFavorite(id){const saved=favorites.has(id),response=await fetch(`/api/favorites/${id}`,{method:saved?"DELETE":"POST"});if(response.status===401){showToast("Sign in as a buyer to save products");setTimeout(()=>location.href="auth.html",1000);return}if(response.ok){saved?favorites.delete(id):favorites.add(id);renderProducts();showToast(saved?"Removed from saved products":"Product saved")}}
async function loadFavorites(){try{const response=await fetch("/api/favorites");if(response.ok)favorites=new Set(await response.json());renderProducts()}catch{}}
async function addToCart(id,selection=null){const base=products.find(p=>String(p.id)===String(id));if(base.backendId&&!selection){const detail=await fetch(`/api/products/${base.backendId}`).then(r=>r.json());if(detail.variants?.length){location.href=`product.html?id=${base.backendId}`;return}}const product={...base,variantId:selection?.variantId||null,variantLabel:selection?.variantLabel||null,price:base.price+Number(selection?.priceAdjustment||0)};if(cart.length&&(cart[0].currency!==product.currency||Boolean(cart[0].backendId)!==Boolean(product.backendId)||(cart[0].backendId&&cart[0].merchant!==product.merchant))){showToast("Finish this merchant order before starting another");toggleCart(true);return}cart.push(product);renderCart();showToast(`${product.variantLabel||product.name} added to your bag`)}
function renderCart(){
  $("#cartCount").textContent=cart.length;
  $("#cartItems").innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-line"><div class="mini-art" style="background:${p.color}">${p.image_url?`<img src="${p.image_url}" alt="">`:p.emoji}</div><div><h3>${p.name}</h3><small>${p.variantLabel||p.merchant}</small></div><div><strong>${money(p.price,p.currency)}</strong><br><button class="remove" data-remove="${i}">Remove</button></div></div>`).join(""):`<div class="empty-cart"><b>🧺</b><strong>Your bag is empty</strong><p>Find something that feels like home.</p></div>`;
  document.querySelectorAll("[data-remove]").forEach(b=>b.addEventListener("click",()=>{cart.splice(Number(b.dataset.remove),1);renderCart()}));
  const subtotal=cart.reduce((s,p)=>s+p.price,0),currency=cart[0]?.currency;
  $("#cartSummary").innerHTML=cart.length?`<div class="summary-row total"><span>Products</span><span>${money(subtotal,currency)}</span></div><div class="summary-row"><span>Delivery</span><span>Calculated at checkout</span></div><p class="currency-note">The merchant sets delivery for your destination. You send ${currency}; Soko does not convert currency.</p><button class="button primary checkout" id="checkoutButton">Continue to checkout →</button>`:"";
  $("#checkoutButton")?.addEventListener("click",openCheckout);
}
function toggleCart(open){$("#cartDrawer").classList.toggle("open",open);$("#drawerBackdrop").classList.toggle("open",open);$("#cartDrawer").setAttribute("aria-hidden",String(!open));}
function toggleModal(open){$("#modalBackdrop").classList.toggle("open",open)}
function orderTotals(){const subtotal=cart.reduce((sum,item)=>sum+item.price,0);return{subtotal,currency:cart[0].currency}}
function openCheckout(){checkoutStep=1;currentOrder=null;toggleCart(false);$("#checkoutBackdrop").classList.add("open");renderCheckout()}
function closeCheckout(){$("#checkoutBackdrop").classList.remove("open")}
function renderCheckout(){$("#checkoutProgress").innerHTML=[1,2,3].map(step=>`<span class="progress-step ${step<=checkoutStep?"active":""}"></span>`).join("");if(checkoutStep===1)renderDelivery();if(checkoutStep===2)renderPayment();if(checkoutStep===3)renderSuccess()}
function renderDelivery(){
  const t=orderTotals();
  $("#checkoutContent").innerHTML=`<div class="checkout-heading"><span class="kicker">STEP 1 OF 3 · DELIVERY</span><h2 id="checkoutTitle">Where should it go?</h2><p>The merchant’s delivery price is selected from your destination.</p></div><form id="deliveryForm" class="checkout-form"><label>First name<input name="firstName" required autocomplete="given-name" value="${safe(deliveryDetails.firstName)}"></label><label>Last name<input name="lastName" required autocomplete="family-name" value="${safe(deliveryDetails.lastName)}"></label><label class="wide">Email address<input name="email" required type="email" autocomplete="email" placeholder="For receipts and tracking" value="${safe(deliveryDetails.email)}"></label><label class="wide">Delivery address<input name="address" required autocomplete="street-address" value="${safe(deliveryDetails.address)}"></label><label>City<input name="city" required autocomplete="address-level2" value="${safe(deliveryDetails.city)}"></label><label>Postcode / ZIP<input name="postcode" required autocomplete="postal-code" value="${safe(deliveryDetails.postcode)}"></label><label class="wide">Delivery country<select name="country" required><option value="">Select country</option>${["United Kingdom","United States","Canada","Australia","France","Germany","Other European country"].map(c=>`<option ${deliveryDetails.country===c?"selected":""}>${c}</option>`).join("")}</select></label><div class="order-review wide"><div class="review-line total"><span>Products</span><span>${money(t.subtotal,t.currency)}</span></div><div class="review-line"><span>Delivery</span><span>Added after destination check</span></div></div><div class="checkout-actions wide"><button class="back-button" type="button" id="backToBag">← Back to bag</button><button class="button primary" type="submit">Calculate delivery →</button></div></form>`;
  $("#backToBag").addEventListener("click",()=>{closeCheckout();toggleCart(true)});$("#deliveryForm").addEventListener("submit",preparePaymentOrder);
}
async function preparePaymentOrder(e){e.preventDefault();deliveryDetails=Object.fromEntries(new FormData(e.target));const databaseItems=cart.filter(p=>p.backendId);if(databaseItems.length){const button=e.target.querySelector("button[type=submit]");button.disabled=true;try{const response=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:databaseItems.map(p=>({productId:p.backendId,variantId:p.variantId})),customerName:`${deliveryDetails.firstName} ${deliveryDetails.lastName}`,destination:`${deliveryDetails.city}, ${deliveryDetails.country}`,deliveryCountry:deliveryDetails.country})}),result=await response.json();if(response.status===401){showToast("Sign in as a buyer to create a payment reference");setTimeout(()=>location.href="auth.html",1200);return}if(!response.ok)throw Error(result.error);const initResponse=await fetch(`/api/payments/${result.id}/initialize`,{method:"POST",headers:{"Content-Type":"application/json"}}),providerData=await initResponse.json();if(!initResponse.ok)throw Error(providerData.error);currentOrder={...result,...providerData,delivery:deliveryDetails,items:cart.map(p=>({id:p.id,variant:p.variantLabel})),market:cart[0].market}}catch(err){showToast(err.message);button.disabled=false;return}}checkoutStep=2;renderCheckout()}
function paymentRow(label,value,copy=false){return `<div class="payment-detail"><span>${label}</span><strong>${value}</strong>${copy?`<button class="copy-button" data-copy="${value}">Copy</button>`:"<i></i>"}</div>`}
function renderPayment(){
  const t=orderTotals(),code=currentOrder?.currency||t.currency,total=currentOrder?.total||t.total,route=paymentRoutes[code];if(!currentOrder)currentOrder={reference:`SOKO-${code}-${String(Date.now()).slice(-6)}`,currency:code,total,delivery:deliveryDetails,id:`DEMO-${Date.now()}`};
  $("#checkoutContent").innerHTML=`<div class="checkout-heading"><span class="kicker">STEP 2 OF 3 · LOCAL PAYMENT</span><h2 id="checkoutTitle">Send ${money(total,code)}</h2><p>Send funds you already hold in ${code}. Soko performs no currency conversion.</p></div><div class="payment-warning"><strong>Prototype only:</strong> These are demonstration collection details. A licensed partner will hold and settle production funds.</div><div class="payment-card"><header><strong>${route.method} · safeguarded collection</strong><span class="demo-tag">DEMO PROVIDER</span></header>${paymentRow("Provider",route.bank)}${paymentRow("Recipient","Soko marketplace collection")}${paymentRow("Account / wallet",route.account,true)}${paymentRow("Payment reference",currentOrder.reference,true)}${paymentRow("Exact amount",money(total,code),true)}</div><div class="confirm-box"><strong>Provider confirmation</strong><p>Production orders update only after a signed event from the licensed provider. This button sends an idempotent development-provider event.</p><button class="button cream" id="simulatePayment">Simulate provider confirmation →</button><div class="prototype-note">No real money moves.</div></div><div class="checkout-actions"><button class="back-button" id="backToDelivery">← Review delivery details</button></div>`;
  if(currentOrder.subtotal!==undefined)$("#checkoutContent .checkout-heading").insertAdjacentHTML("afterend",`<div class="order-review"><div class="review-line"><span>Products</span><span>${money(currentOrder.subtotal,code)}</span></div><div class="review-line"><span>Delivery</span><span>${money(currentOrder.deliveryFee,code)}</span></div><div class="review-line total"><span>Total</span><span>${money(total,code)}</span></div></div>`);document.querySelectorAll("[data-copy]").forEach(button=>button.addEventListener("click",()=>{navigator.clipboard?.writeText(button.dataset.copy);showToast("Copied")}));$("#backToDelivery").addEventListener("click",()=>{checkoutStep=1;renderCheckout()});if(currentOrder.provider==="paystack"){$("#simulatePayment").textContent="Continue securely with Paystack →";$("#simulatePayment").addEventListener("click",()=>location.href=currentOrder.paymentUrl)}else $("#simulatePayment").addEventListener("click",confirmPayment);
}
async function confirmPayment(){if(currentOrder.id.startsWith("SK")){try{const response=await fetch(`/api/payments/${currentOrder.id}/simulate`,{method:"POST",headers:{"Content-Type":"application/json"}}),result=await response.json();if(!response.ok)throw Error(result.error);currentOrder.status=result.status}catch(e){showToast(e.message);return}}else currentOrder.status="Payment confirmed";currentOrder.createdAt=new Date().toISOString();localStorage.setItem("sokoLatestOrder",JSON.stringify(currentOrder));checkoutStep=3;renderCheckout();cart=[];renderCart()}
function renderSuccess(){$("#checkoutContent").innerHTML=`<div class="success-view"><div class="success-mark">✓</div><span class="kicker">PAYMENT CONFIRMED · PROTOTYPE</span><h2 id="checkoutTitle">Your order is with us.</h2><p>Thanks, ${safe(currentOrder.delivery.firstName)}. We’ll send tracking updates to ${safe(currentOrder.delivery.email)}.</p><span class="order-number">ORDER ${currentOrder.id}</span><div class="timeline"><div class="timeline-item done"><span class="timeline-dot"></span><div><h3>Payment confirmed</h3><p>Your ${currentOrder.currency} payment has been matched to this order.</p></div></div><div class="timeline-item"><span class="timeline-dot"></span><div><h3>Merchant preparing order</h3><p>The merchant will confirm and prepare your items next.</p></div></div><div class="timeline-item"><span class="timeline-dot"></span><div><h3>On its way</h3><p>Tracking appears here once the delivery partner collects it.</p></div></div><div class="timeline-item"><span class="timeline-dot"></span><div><h3>Delivered</h3><p>Your order reaches ${safe(currentOrder.delivery.city)}.</p></div></div></div><button class="button primary" id="finishOrder">Continue shopping →</button><p class="prototype-note">This is a simulated order. No payment or delivery was created.</p></div>`;$("#finishOrder").addEventListener("click",()=>{closeCheckout();currentOrder=null;$("#marketplace").scrollIntoView({behavior:"smooth"})})}
let toastTimer;function showToast(message){$("#toast").textContent=message;$("#toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),2200)}
$("#filters").addEventListener("click",e=>{if(!e.target.dataset.filter)return;filter=e.target.dataset.filter;document.querySelectorAll("#filters button").forEach(b=>b.classList.toggle("active",b===e.target));renderProducts()});
$("#productSearch").addEventListener("input",e=>{searchTerm=e.target.value.trim().toLowerCase();renderProducts()});$("#countryFilter").addEventListener("change",e=>{countryFilter=e.target.value;renderProducts()});
$("#cartButton").addEventListener("click",()=>toggleCart(true));$("#closeCart").addEventListener("click",()=>toggleCart(false));$("#drawerBackdrop").addEventListener("click",()=>toggleCart(false));
$("#merchantButton")?.addEventListener("click",()=>toggleModal(true));$("#modalClose").addEventListener("click",()=>toggleModal(false));$("#modalBackdrop").addEventListener("click",e=>{if(e.target===$("#modalBackdrop"))toggleModal(false)});
$("#merchantForm").addEventListener("submit",e=>{e.preventDefault();toggleModal(false);e.target.reset();showToast("You’re on the merchant early-access list")});
$("#checkoutClose").addEventListener("click",closeCheckout);$("#checkoutBackdrop").addEventListener("click",e=>{if(e.target===$("#checkoutBackdrop"))closeCheckout()});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){toggleCart(false);toggleModal(false);closeCheckout()}});
renderProducts();renderCart();loadDatabaseProducts();loadFavorites();
